### ISSUE TITLE
BUG: Web site legal notices are missing.

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#11]
ISSUE 1: Policy consent button for this web application is missing 
ISSUE 2:  Link to https://www.gatesfoundation.org/Privacy-and-Cookies-Notice (as part of the first window) is missing.

Same or similar to page below:

![image](https://user-images.githubusercontent.com/74386190/135554946-d04fdd49-d83d-45da-8a0b-fe4da124427a.png)

**Comment by dkong-bmgf** [comment]
dialog added.  Pls take a look.
