### ISSUE TITLE
BUG: Beta parameter accepts Zero value but throws and Error

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#19]
## Repro:
- Open https://leakyvaccine-acc.bmgf.io/
- Set Beta parameter to Zero (slide it all the way to the left)

## Expected:
- The value is taken and evaluated according with the model expectations, this is, if  the Beta parameter is never expected to be Zero, then the UI slider should have a minimum value set to greater than zero, Or, if the Beta parameter could be Zero, then the handle the case appropriately. 

![image](https://user-images.githubusercontent.com/74386190/141012255-91aadbfa-5c80-434c-b660-2caf67d434e5.png)

**Comment by DKong-IDM** [comment]
@herbeck, can min value of beta be 0.001?  Thx!

**Comment by DKong-IDM** [comment]
fixed. Pls take a look

**Comment by menriquez-IDM** [comment]
Verified - this issue is fixed.
