### ISSUE TITLE
BUG:  sexual contacts per day  (c) parameter set to zero generates an error.

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#20]
## Repro:
Open https://leakyvaccine-acc.bmgf.io/
Set _sexual contacts per day_: parameter to Zero (slide it all the way to the left)
## Expected:
The value is taken and evaluated according with the model expectations, this is, IF the _sexual contacts per day_ parameter is never expected to be Zero, then the UI slider should have a minimum value set to greater than zero, Or, if the _sexual contacts per day_ parameter could be Zero, then the model/application should handle the case appropriately.

![image](https://user-images.githubusercontent.com/74386190/141015974-4707c32f-a9eb-4c8c-983c-f600c7665f6a.png)

**Comment by DKong-IDM** [comment]
fixed. Pls take a look

**Comment by menriquez-IDM** [comment]
Tested - Issue is gone.
