### ISSUE TITLE
BUG: prev (population prevalence of viremic individuals) parameter generates an error if set to Zero

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#21]
## Repro:
Open https://leakyvaccine-acc.bmgf.io/
Go to "initial example plots"
Set _prev (population prevalence of viremic individuals)_ parameter to Zero (slide it all the way to the left)
## Expected:
The value is taken and evaluated according with the model expectations, this is, IF the _prev (population prevalence of viremic individuals)_ parameter is never expected to be Zero, then the UI slider should have a minimum value set to greater than zero, Or, if the _prevalence_ parameter could be Zero, then the model/application should handle the case appropriately.

![image](https://user-images.githubusercontent.com/74386190/141017070-cf0a42c8-a12d-4f69-88e2-3b4a3c653fc2.png)

**Comment by DKong-IDM** [comment]
@herbeck , pls  advise if prev can be zero.

**Comment by DKong-IDM** [comment]
fixed. Pls take a look

**Comment by menriquez-IDM** [comment]
Scenario has been verified - issue as been fixed by setting the min value to 0.001
