### ISSUE TITLE
BUG: Parameter sweeps figure errors

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#22]
## Repro:
- Open https://leakyvaccine-acc.bmgf.io/
- Go to "parameter sweeps" tab
- wait for the images to render

## Actual:
Only one of 5 figures render, the first one, the other ones display the error: 
"An error has occurred. Check your logs or contact the app author for clarification."

![image](https://user-images.githubusercontent.com/74386190/141018954-8e683a6b-444d-41f5-8788-410b71eae811.png)

**Comment by DKong-IDM** [comment]
fixed. Please take a look.

**Comment by menriquez-IDM** [comment]
Tested.  Looks good.
