### ISSUE TITLE
BUG: Parameter sweeps - All graphics get broken when moving prevalence

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#23]
## Repro
- Open Go to  https://leakyvaccine-acc.bmgf.io/
- Go to Parameter sweeps tab
- Leaving the default values (below), move prevalence to 0.2 (or higher)
- - ->Beta=0.004
- - ->C=0.25
- - ->Epsilon= 0.3
- - ->inc = 0.04 
- - -> sample size = 5,000
## Actual
- All charts get broken

![image](https://user-images.githubusercontent.com/74386190/141039890-65b3eccb-d00e-4864-833b-1bba92dcea3e.png)

**Comment by DKong-IDM** [comment]
fixed. Pls take a look

**Comment by menriquez-IDM** [comment]
Verified on https://leakyvaccine-acc.bmgf.io/ - this issue is fixed.
