### ISSUE TITLE
BUG: Parameter Sweeps - nsteps doesn't allow to select values between 1 and 5

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#31]
## REPRO
- Go to https://leakyvaccine-acc.bmgf.io/
- navigate to parameter sweeps tab
-try to move the nsteps parameter

## ACTUAL
- I couldn't set a nteps = 2, or 3 or 4... it only accepts 1 or 5. 
- Please note that the default value is set to 3, but once the parameter is moved to 1 or 5, it stops 'working'

**Comment by JHerbeck-IDM** [comment]
I will fix that in the slider section in the TabContent

**Comment by menriquez-IDM** [comment]
Tested, it looks good.
