### ISSUE TITLE
BUG: Parameter sweeps - Figures 2 and 3 missing description.

### ISSUE THREAD

**Issue by menriquez-IDM** [InstituteforDiseaseModeling/LeakyVaccine#39]
## REPRO
- Open  https://leakyvaccine-acc.bmgf.io/
- Go to Parameter sweeps tab
- Wait for the chart to render

## ACTUAL
- figure 1 has a description but figures 2 and 3 don't.

## EXPECTED
- Figures have a brief explanation of the data presented to the user.

![image](https://user-images.githubusercontent.com/74386190/142376304-43b5c604-9f0a-4bfc-b02b-25fbadd892c2.png)

**Comment by dkong-bmgf** [comment]
Looks like  it was fixed. pls take a look.

**Comment by menriquez-IDM** [comment]
I reviewd it, now it looks fine.
